name: PR assignment

on:
    pull_request_target:
        types: [opened, reopened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: 'Auto-assign PR'
              uses: pozil/auto-assign-issue@v1
              with:
                  assignees: socuul
                  allowNoAssignees: true
